apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shared-app-ingress
spec:
  rules:
    - http:
        paths:
          # Route traffic for Log Output application
          - path: /
            pathType: Prefix
            backend:
              service:
                name: log-output-svc
                port:
                  number: 80

          # Route traffic for Ping Pong application (adjust path/rewrites as needed)
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: ping-pong-svc
                port:
                  number: 8666
