apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: hismyhill/todo-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: APP_PORT
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: INTERNAL_FETCH_URL
            - name: CLIENT_POST_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: BROWSER_POST_PATH
            - name: TODO_USER
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: POSTGRES_USER
            - name: TODO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-app-secrets
                  key: POSTGRES_PASSWORD
            - name: TODO_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: DATABASE_HOST
            - name: TODO_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: DATABASE_PORT
            - name: TODO_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: POSTGRES_DB
            - name: DATABASE_URL
              value: "postgres://$(TODO_USER):$(TODO_PASSWORD)@$(TODO_HOST):$(TODO_PORT)/$(TODO_DB)"
          ports:
            - containerPort: 3000
