apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: hismyhill/todo-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKEND_URL
              value: "http://todo-app-svc:2345/todos"
            - name: PORT
              value: "3000"
