apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output-server
          image: hismyhill/log_output:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
            - name: MODE
              value: "reader" # Standard server mode which fetches and serves HTTP data
            - name: PINGPONG_URL
              value: "http://ping-pong-svc:8666/pings" # Matches your 8666 cluster service port
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/app/config
      volumes:
        - name: config-volume
          configMap:
            name: log-output-config
