apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      securityContext:
        fsGroup: 2000
      volumes:
        - name: output-volume
          persistentVolumeClaim:
            claimName: output-pvc
      containers:
        # Container 1: The Writer (Using your app image)
        - name: log-generator
          image: hismyhill/log_output:v2.0 # <--- SAME IMAGE
          env:
            - name: MODE
              value: "writer"
          securityContext:
            runAsUser: 0 # Force container to execute as root
            runAsGroup: 0
          volumeMounts:
            - name: output-volume
              mountPath: /usr/share/app/files

        # Container 2: The Reader (Using your app image)
        - name: log-web-server
          image: hismyhill/log_output:v2.0 # <--- SAME IMAGE
          env:
            - name: MODE
              value: "reader"
          ports:
            - containerPort: 3000
          securityContext:
            runAsUser: 0 # Force container to execute as root
            runAsGroup: 0
          volumeMounts:
            - name: output-volume
              mountPath: /usr/share/app/files
