apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output-server
          image: hismyhill/log_output:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MODE
              value: "reader" # Standard server mode which fetches and serves HTTP data
            - name: PINGPONG_URL
              value: "http://ping-pong-svc:8666/pings" # Update with your exact Ping Pong service name/port
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
